catsitter/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

catsitter/catsitter/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catsitter_main.urls', namespace='catsitter_main')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

catsitter/catsitter_main/urls.py
# ice_cream/urls.py
from django.urls import path
from . import views


app_name = 'catsitter_main'

urlpatterns = [
    # Главная страница
    path('', views.index, name='index'),
    # Страница со списком сортов мороженого
    #path('catsitter/', views.catsitter_list, name='catsitter_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    # Отдельная страница с информацией о сорте мороженого
    path('catsitter/<int:post_id>/', views.catsitter_detail, name='catsitter_detail'),
    path('create/', views.post_create, name='post_create'),
    path('catsitter/<int:post_id>/edit/', views.post_edit, name='post_edit'),
] 

catsitter/catsitter_main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

User = get_user_model()

class Questionnaire(models.Model):
    name = models.TextField()
    description = models.TextField()
    location = models.TextField()
    price = models.IntegerField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='questionnaire'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='catsitter_main/',
        blank=True
    )
    def __str__(self):
        return self.name

catsitter/catsitter_main/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Questionnaire

User = get_user_model()

 
class PostForm(forms.ModelForm):

    class Meta:
        model = Questionnaire
        fields = ('description', 'location', 'price', 'image')
        labels = {'description': 'Описание', 'location': 'Локация', 'price': 'цена', 'image': 'изображение'}

    def clean_text(self):
        data = self.cleaned_data['description']
        if Questionnaire.description == '':
            raise forms.ValidationError(
                'Поле, текст обязателен для заполнения!')
        return data

catsitter/catsitter_main/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator


from .forms import PostForm
from .models import Questionnaire, User


def get_page_paginator(request, posts):
    page_namber = request.GET.get('page')
    paginator = Paginator(posts, settings.POSTS_NUM)
    page_obj = paginator.get_page(page_namber)
    return page_obj

# Главная страница
def index(request):
    questionnaires = Questionnaire.objects.select_related('author')
    page_obj = get_page_paginator(request, questionnaires)
    context = {
        'questionnaires': questionnaires,
        'page_obj': page_obj,
    }
    return render(request, 'catsitter_main/index.html', context)

#«Добавлены urls и view-функции»
# Страница со списком мороженого
def catsitter_list(request):
    template = 'catsitter_main/catsitter_list.html'
    return render(request, template)



# Страница с информацией об одном сорте мороженого;
# view-функция принимает параметр pk из path()

def catsitter_detail(request, post_id):
    post = get_object_or_404(Questionnaire, pk=post_id)
    posts_count = Questionnaire.objects.filter(author=post.author).count()
    author = User.objects.get(username=post.author)
    # Здесь код запроса к модели и создание словаря контекста
    context = {
        'post': post,
        'author': author,
        'posts_count': posts_count,
    }
    return render(request, 'catsitter_main/catsitter_detail.html', context)

def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = Questionnaire.objects.filter(author=author)
    page_obj = get_page_paginator(request, posts)
    count_post = posts.count
    # Здесь код запроса к модели и создание словаря контекста
    context = {
        'author': author,
        'posts': posts,
        'page_obj': page_obj,
        'count_post': count_post,
    }
    return render(request, 'catsitter_main/profile.html', context)

@login_required
def post_create(request):
    form = PostForm(request.POST or None,  files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('catsitter_main:profile', request.user.username)
    return render(request, 'catsitter_main/post_create.html', {'form': form})
        

@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Questionnaire, pk=post_id)
    form = PostForm(request.POST or None, files=request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save()
        post.save()
        return redirect('catsitter_main:catsitter_detail', post_id=post_id)

    # Здесь код запроса к модели и создание словаря контекста
    context = {
        'post': post,
        'form': form,
        'is_edit': True,

        }
    return render(request, 'catsitter_main/post_create.html', context)

catsitter/templates/catsitter_main/catsitter_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Пост {{ post.description|truncatechars:30 }}
    {% endblock %}
    {% block content %}
    
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>

              </a>
            </li>
       
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{ post.author.post.count }}
              <span ><!-- --></span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'catsitter_main:profile' post.author %}">
                
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>Локация: {{ post.location }}</p>
          <p>Стоимость, руб.: {{ post.price }}</p>
          {% thumbnail post.image "960x339" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>Описание: {{ post.description|linebreaksbr }}</p>

          {% if user == post.author %}
    <button type="submit" class="btn btn-primary">
      <a class="btn btn-primary" href="{% url 'catsitter_main:post_edit' post.id %}">
        Редактировать запись
      </a>
    </button>
    {% endif %}
  </article>
</div>
{% endblock %}

catsitter/templates/catsitter_main/catsitter_list.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    {% block title %}<title>Catsitter</title>{% endblock %}
  </head>
  <body>
    <header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->    
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'catsitter_main:index' %}"
            <img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>      
    </header>
    <main>
      {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>Catsitter</h1>
        <h2>Выберите кэтситтера!</h2>
        <p>
          Группа тайных поклонников графа.
        </p>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 30 июля 1854
            </li>
          </ul>      
          <p>
            [Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется мнѣ.
            Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо. 
            Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ прикомандироваться 
            къ казачьей батареѣ; совѣтъ, которому я не послѣдую. Желчно спорилъ вечеромъ съ Фриде 
            и Бабарыкинымъ, ругалъ Сержпутовскому и ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю с
            ебѣ за нынѣшній день. (3)
          </p>         
        </article>
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 29 июля 1854
            </li>
          </ul> 
          <p>
            Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки 
            съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ, 
            что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень 
            веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня; 
            отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками. 
            — Тогда бы я всегда былъ веселъ и почти всегда счастливъ. 
            Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ, 
            чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ 
            накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за 
            безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
          </p>      
        </article>
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
            </li>
            <li>
              Дата публикации: 28 июля 1854
            </li>
          </ul> 
          <p>
            Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ. 
            Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и 
            Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ 
            хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и 
            Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности, 
            днемъ своимъ очень доволенъ. (1)
          </p>
        </article>
        <!-- под последним постом нет линии -->
      </div>
      {% endblock %} 
    </main>
    <footer class="page-footer font-small blue border-top">
      <div class="footer-copyright text-center py-3">© 2020 Copyright 
        <p><span style="color:red">Ya</span>tube</p> 
      </div>    
    </footer>
  </body>
</html>

catsitter/templates/catsitter_main/index.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>
        
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    {% block title %}
    <title> Главная </title>
    {% endblock %}
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
     
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>Возьмем кота в гости, пока вы в отъезде!</h1>
        <img src="{% static 'img/manul.jpg' %}" width="700" height="430" class="d-inline-block align-top" alt="">
        {% for post in page_obj %}

         
          {% include 'includes/article.html' %}
        

        {% endfor %} 
        </article>
        <hr>
        <!-- под последним постом нет линии -->
      </div>  
  
      {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->         
    <footer class="border-top text-center py-3">
        {% include 'includes/footer.html' %}
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

catsitter/templates/catsitter_main/post_create.html
{% extends 'base.html'%}
{% block title %}
{% if is_edit %}
Редактировать запись
{% else %}
Новая запись
{% endif %}
{% endblock %}    
  {% block content %} 
    
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">  
                {% if is_edit %}
               Редактировать пост
                {% else %}
               Новый пост
                {% endif %}            
              </div>
              <div class="card-body"> 
                {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}       
                <form method="post" enctype="multipart/form-data">   

                  {% csrf_token %}
                  {{ form.as_p }}
                  <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}></div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                      Сохранить
                      {% else %}
                      Добавить
                      {% endif %} 
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    
{% endblock %}

catsitter/templates/catsitter_main/profile.html
{% extends 'base.html'%}

    {% block title %}
     Профайл пользователя{{ user }}
    {% endblock title %}
    {% block content %}
    <h2>Все заказы пользователя {{ author }}</h2>
      <h3>Всего заказов: {{ count_post }}</h3>
        {% for post in page_obj %}
        {% include 'includes/article.html' %}
           {% endfor %} 
          <!-- Здесь подключён паджинатор --> 
        {% include 'catsitter_main/includes/paginator.html' %}
  {% endblock content %}